---
name: deploy
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: dsv-github-action
        uses: DelineaXPM/dsv-github-action@v1.0.4
        # uses: delineaxpm/dsv-github-action@main # renovate: tag=v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          domain: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          setEnv: true
          retrieve: |
            [
               {"secretPath": "ci:dsv-github-action-demo:dsvdemo", "secretKey": "aws_keyid", "outputVariable": "AWS_ACCESS_KEY_ID"},
               {"secretPath": "ci:dsv-github-action-demo:dsvdemo", "secretKey": "aws_ssecret_access_key", "outputVariable": "AWS_SECRET_ACCESS_KEY"},
               {"secretPath": "ci:dsv-github-action-demo:awsbucket", "secretKey": "aws_bucket", "outputVariable": "AWS_BUCKET_NAME"}
            ]
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.dsv.outputs.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ steps.dsv.outputs.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp index.html s3://dsvgithubdemo
