---
name: deploy
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:
# permissions:
#   contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - name: dsv-github-action
        uses: DelineaXPM/dsv-github-action@v1.0.4
        # uses: delineaxpm/dsv-github-action@main # renovate: tag=v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          domain: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          setEnv: true
          retrieve: |
            [
             {"secretPath": "test:sdk:simple", "password": "value1"}
            ]
      - name: validate-first-value
        if: always()
        run: |
          echo ${{ steps.dsv.outputs.RET_1 }}
          echo ${{ env.RET_1 }}
