---
name: deploy
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - id: dsv
        uses: DelineaXPM/dsv-github-action@v2.0.1
        with:
          domain: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          retrieve: |
            [
               {"secretPath": "ci:dsv-github-action-demo:dsvdemo", "secretKey": "aws_keyid", "outputVariable": "AWS_ACCESS_KEY_ID1"}
              
            ]
      - name: Write Bucket name
        run: echo ${{ env.AWS_ACCESS_KEY_ID1 }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID1 }}
          #aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY1 }}
          aws-region: us-east-2
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp index.html s3://${{ secrets.AWS_BUCKET }}
