---
name: deploy
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:  
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      env.SECRETVAL1: ""
      env.SECRETVAL2: ""
      env.SECRETVAL3: "3"
    steps:
      - uses: actions/checkout@v3
      - id: init
        run: |
          echo "::add-mask::${{ env.SECRETVAL1 }}"
          echo "::add-mask::${{ env.SECRETVAL2 }}"
          echo "::add-mask::${{ env.SECRETVAL3 }}"
      - id: dsv
        uses: DelineaXPM/dsv-github-action@v2.0.1
        with:
          domain: ${{ secrets.DSV_SERVER }}
          clientId: ${{ secrets.DSV_CLIENT_ID }}
          clientSecret: ${{ secrets.DSV_CLIENT_SECRET }}
          retrieve: |
            [
               {"secretPath": "ci:dsv-github-action-demo:dsvdemo", "secretKey": "aws_keyid", "outputVariable": "SECRETVAL1"},
               {"secretPath": "ci:dsv-github-action-demo:dsvdemo", "secretKey": "aws_ssecret_access_key", "outputVariable": "SECRETVAL2"},
               {"secretPath": "ci:dsv-github-action-demo:awsbucket", "secretKey": "aws_bucket", "outputVariable": "SECRETVAL3"}  
            ]
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.SECRETVAL1 }}
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to the test website with the AWS CLI
        run: |
          aws s3 cp index.html s3://${{ secrets.AWS_BUCKET }}
  
